export class ViewProduct {
    ctName: string;
    catName: string;
    brName: string;
    id: Number;
    pimsId: Number;
    catId: Number;
    brId:Number;
    sku: string;
    barcode: string;
    asin: string;
    bestSeller: string;
    newProduct: Number;
    recommended:Number;
    sort: Number;
    name: string;
    images: string;
    refUrl: string;
    taxation: Number;
    moq: Number;
    retailPrice: Number;
    supplyPrice:Number;
    salePrice: Number;
    pricingTable: string;
    stock: Number;
    capacity: string;
    ingredient: string;
    tags: string;
    manufactured: string;
    distributor: string;
    producerCtId: string;
    producerArea: string;
    msds: string;
    certificate: string;
    discontinued: Number;
    discontinuedDate: Date; 
    discontinuedDateUpdated: Date;
    validCountry: string;
    invalidCountry: string;
    comments: string;
    contents: string;
    favoriteCount: Number;
    inquiryCount: Number;
    viewCount: Number;
    status: string;
    statusUpdated: Date;
    created: Date;
    updated: Date;
    deleted: Date;
}